name: Build Arch ISO
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      uses: actions/checkout@v3
    - name: Build In Docker
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        useradd builduser -m
        passwd -d builduser
        pacman-key --init
        pacman-key --populate
        pacman -Syu --noconfirm --needed reflector curl archiso wget zip
        reflector --country $(curl ipv4.myip.wtf/text/country) --sort rate -n 5 --save /etc/pacman.d/mirrorlist
        pacman -S --noconfirm --needed sudo git base-devel
        curl https://aur.chaotic.cx/mirrorlist.txt -o /etc/pacman.d/chaotic-mirrorlist
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser ./
        sudo mkarchiso -v -w workdir/ -o out/ . 
        cd out
        zip blendOS-T2-$(date +%Y.%m.%d)-T2-x86_64.zip *.iso
        split -d -b 1900M blendOS-T2-$(date +%Y.%m.%d)-T2-x86_64.zip blendOS-T2-$(date +%Y.%m.%d)-T2-x86_64.z 
        rm blendOS-T2-$(date +%Y.%m.%d)-T2-x86_64.zip *.iso
        EOF

        docker run --privileged -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
    
    - name: Upload Built ISO
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      uses: actions/upload-artifact@v3
      with:
        name: built-iso
        path: ${{ github.workspace }}/out/*
    - name: Create Tag
      id: create_tag
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      run: |
        export TAG=$(date +%Y.%m.%d)
        echo "tag=${TAG}-t2" >> $GITHUB_OUTPUT
        echo $TAG
    - name: Release
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      uses: softprops/action-gh-release@v1
      with:
         files: |
           ${{ github.workspace }}/out/*
         tag_name: ${{ steps.create_tag.outputs.tag }}
         name: blendOS T2 V2 GNOME edition 
         draft: ${{ contains(github.event.head_commit.message, '[draft]') }}
         prerelease: ${{ contains(github.event.head_commit.message, '[prerel]') }}
         body: |
           It's here!
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
